name: linting, testing, building, UI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting ts
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit test
        run: npm run test:unit
      - name: Build Storybook
        run: npm run build-storybook

      - name: Start Storybook server
        run: npx http-server storybook-static --port 6006 &
        env:
          NODE_ENV: test
      - name: Wait for Storybook to start
        run: npx wait-on http://localhost:6006
      - name: Run visual tests
        run: npx playwright test
      - name: Upload visual test report if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/